### ISSUE TITLE
Connect Wallet Doesn't Work

### ISSUE THREAD

**Issue by futjrnaut** [M3-org/upstreet-sdk#5]
Win10 using Brave Browser Shields are down  
Go to upstreet.ai 
Try to connect Metamask 
Metamask is connected to Mainnet 
getting this error in the console on click 

requestProvider.js:2 Uncaught (in promise) Error: Request method wallet_switchEthereumChain is not supported
    at a.request (requestProvider.js:2:512806)
    at Fq (localstorage-manager-c556044e.js:43:201889)
    at qq (localstorage-manager-c556044e.js:43:201983)
    at e (localstorage-manager-c556044e.js:43:202137)
    at Object.Nb (globals-47228b43.js:29:10464)
    at Tb (globals-47228b43.js:29:10633)
    at Ub (globals-47228b43.js:29:10699)
    at nf (globals-47228b43.js:29:33658)
    at se$1 (globals-47228b43.js:29:34135)
    at globals-47228b43.js:29:39597
    at Rk (globals-47228b43.js:32:40770)
    at Jb (globals-47228b43.js:29:9554)
    at hd (globals-47228b43.js:29:35564)
    at fd$1 (globals-47228b43.js:29:18595)
    at ed (globals-47228b43.js:29:18341)
    at HTMLDivElement.r (analytics-4852ee6d.js:19:1490)
    
    Metamask extension isn't called / pops up. 
    
    
    Expected : 
    Metamask pops and connects
    
    will put other experiences here

**Comment by futjrnaut** [comment]
chrome works
